services:
  autodrive:
    build: .
    container_name: autodrive_api
    ports:
      - 8082:8082
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=rootuser
      - MONGO_PASSWORD=rootpass
      - MONGO_AUTHDB=admin
      - MONGO_DB=autodrivedb
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
volumes:
  data:
networks:
  default:
    name: mongodb_network